# Generated by Django 4.2.9 on 2024-03-23 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Venue", models.CharField(max_length=5)),
                ("RegisteredDate", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="timetable",
            name="Venue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.venue"
            ),
        ),
    ]
