# Generated by Django 4.2.9 on 2024-03-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_venue_alter_timetable_venue"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="venue",
            name="id",
        ),
        migrations.AlterField(
            model_name="venue",
            name="Venue",
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
