# Generated by Django 4.2.9 on 2024-03-23 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_remove_venue_id_alter_venue_venue"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="department",
            options={"verbose_name": "Department", "verbose_name_plural": "Department"},
        ),
        migrations.RemoveField(
            model_name="instructor",
            name="FirstName",
        ),
        migrations.RemoveField(
            model_name="instructor",
            name="MiddleName",
        ),
    ]
