# Generated by Django 4.2.9 on 2024-03-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_department_options_remove_instructor_firstname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="instructor",
            name="FirstName",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="instructor",
            name="MiddleName",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
